# frontend/netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.12.2"
  NPM_VERSION = "9.6.5"
  NETLIFY = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  # Bỏ qua plugin Next.js của Netlify để tránh lỗi
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Không bao gồm plugin next.js của Netlify

[build.processing]
  skip_processing = true